config/routes.rb
Rails.application.routes.draw do

  root "distributors#index"
  resource :session

  get "signup" => "users#new"
  resources :users

  resources :logs
  resources :managers
  resources :zing_leads
  resources :brokers
  resources :brokerages

  get "distributors/filter/:coverage" => "distributors#index", as: :filtered_distributors
  resources :distributors do
    resources :dcs do
      resources :dc_slots
      resources :dc_cost_lists
    end
  end

  resources :flavors do 
    resources :fgskus
    resources :recipes do
      resources :recipeversions
    end
  end

  resources :ingredients do
    resources :ingredientskus
  end

  resources :parents do
 	  resources :banners do
 	  	resources :stores
		  resources :banner_promos
      resources :authorizations
      resources :banner_cost_retails
 	  end
 	end

end

app/models/distributor.rb
class Distributor < ActiveRecord::Base

	extend FriendlyId
	friendly_id :distributor_name, use: :slugged

	CHANNELS = [ 
		'Natural Grocery',
		'Conventional Grocery',
		'Supplement',
		'Mass Merchandise',
		'Foodservice',
		'Online Affiliate',
		'Own Online',
		'Not Classified'
		]

	validates :distributor_name, uniqueness: true
	validates :country, presence: true
	validates :channel_segment, inclusion: { in: CHANNELS }
	
	belongs_to :broker
	has_many :logs
	has_many :dcs, dependent: :destroy

	scope :distributors_with_current_banners, -> { Distributor.where(id: Dc.dcs_with_current_banners.select(:distributor_id)).order("distributor_name") }
	scope :distributors_with_prospect_banners, -> { Distributor.where(id: Dc.dcs_with_prospect_banners.select(:distributor_id)).order("distributor_name") }

	def dc_count
		self.dcs.count
	end

	def stocking_dcs_count
		self.dcs.where(id: DcSlot.select(:dc_id)).count
	end

	def distributor_current_banner_count
		distributors_with_current_banners.count
	end

	def distributor_prospect_banner_count
		distributors_with_prospect_banners.count
	end

end

app/controllers/distributors_controller.rb
class DistributorsController < ApplicationController

	before_action :set_distributor, only: [:show, :edit, :update, :destroy]

	def index
		 case params[:coverage]
		 	when "current"
				@banners = Banner.current_banners
				@dcs = Dc.dcs_with_current_banners
				@distributors = Distributor.distributors_with_current_banners
		 	when "prospect"
				@banners = Banner.prospect_banners
				@dcs = Dc.dcs_with_prospect_banners
				@distributors = Distributor.distributors_with_prospect_banners
		 	when "priority"
				@banners = Banner.priority_banners
				@dcs = Dc.all.order("dc_name")
				@distributors = Distributor.all.order("distributor_name")
		 	when "no_banners"
		 		@banners = nil
				@dcs = Dc.all.order("dc_name")
				@distributors = Distributor.all.order("distributor_name")
		 	else
				@banners = Banner.all_banners
				@dcs = Dc.all.order("dc_name")
				@distributors = Distributor.all.order("distributor_name")
			end
		@authorizations = Authorization.all.includes(:fgsku).order("fgskus.sizegroup")
		@dc_slots = DcSlot.all.includes(:fgsku).order("fgskus.sizegroup")
		@ranked_flavors = Flavor.ranked_flavors
	end

	def show
	end

	def edit
	end

	def update
		if @distributor.update(distributor_params)
			redirect_to @distributor, notice: "Distributor successfully updated"			
		else
			render :edit
		end		
	end

	def new
		@distributor = Distributor.new
	end

	def create
		@distributor = Distributor.new(distributor_params)
		if @distributor.save			
			redirect_to @distributor, notice: "Distributor successfully created"			
		else
			render :new
		end
	end

	def destroy
		deleted = @distributor.distributor_name
		@distributor.destroy
		redirect_to distributors_path, notice: "#{deleted} deleted"
	end

end

private
	def distributor_params
		params.require(:distributor).permit(  :distributor_name, 
																			    :distributor_contact_first_name,
																			    :distributor_contact_last_name,
																			    :distributor_contact_email,
																			    :distributor_contact_phone,
																			    :distributor_address_1,
																			    :distributor_address_2,
																			    :distributor_city,
																			    :distributor_state,
																			    :distributor_zip,
																			    :distributor_notes,
																			    :channel_segment,
																			    :country,
																					:slug 
																					)
	end

	def set_distributor
#		parameter = :distributor_id || :id
		@distributor = Distributor.find_by!(slug: params[:id])
	end

app/helpers/distributors_helper.rb
module DistributorsHelper


end

app/views/distributors/_distributorform.html.erb
<%= form_for(@distributor) do |f| %>
  <%= render 'shared/errors', object: @distributor %>
	<fieldset>
	<ol>
		<li class="required"><%= f.label "Distributor:" %> <%= f.text_field :distributor_name, size: 65, autofocus: true %></Li>
		<li class="required"><%= f.label :channel_segment %>
			<% Distributor::CHANNELS.each do |channel| %>
				<table>
					<tr>
						<td><%= f.radio_button :channel_segment, channel %></td>
						<td><%= channel %></td>
					</tr>
				</table>
				<% end %>

				</li>
				<li class="required"><%= f.label :country %>
					<% Fgsku::COUNTRIES.each do |country| %>
						<table>
							<tr>
								<td><%= f.radio_button :country, country %></td>
								<td><%= country %></td>
							</tr>
						</table>			
					<% end %>
				</li>	
			
		</Li>
		<li class="required">
			<%= f.label :distributor_contact_first_name %> 
			<%= f.text_field :distributor_contact_first_name %>
		</Li>
		<li class="required">
			<%= f.label :distributor_contact_last_name %> 
			<%= f.text_field :distributor_contact_last_name %>
		</Li>
		<li class="required">
			<%= f.label :distributor_contact_email %> 
			<%= f.text_field :distributor_contact_email %>
		</Li>
		<li class="required">
			<%= f.label :distributor_contact_phone %> 
			<%= f.text_field :distributor_contact_phone %>
		</Li>
		<li class="required">
			<%= f.label :distributor_address_1 %> 
			<%= f.text_field :distributor_address_1 %>
		</Li>
		<li class="required">
			<%= f.label :distributor_address_2 %> 
			<%= f.text_field :distributor_address_2 %>
		</Li>
		<li class="required">
			<%= f.label :distributor_city %> 
			<%= f.text_field :distributor_city %>
		</Li>
		<li class="required">
			<%= f.label :distributor_state %> 
			<%= f.text_field :distributor_state %>
		</Li>
		<li class="required">
			<%= f.label :distributor_zip %> 
			<%= f.text_field :distributor_zip %>
		</Li>
		<li class="required">
			<%= f.label :distributor_notes %> 
			<%= f.text_area :distributor_notes, cols: 40, rows: 7  %>
		</Li>
		<p>
			<%= f.submit %>
			<%= link_to 'CANCEL', parents_path, class: 'button'%>
		</p>
	</fieldset>

<% end %>

app/views/distributors/edit.html.erb
<article>
	<header>

	<h1>Editing <%= @distributor.distributor_name %></h1>
	<%= render 'distributorform' %>

	</header>
</article>

app/views/distributors/index.html.erb
<h1>Distribution Profile: <%= params[:coverage] %></h1>
<%= image_tag("arrow.png") %>
<%= pluralize(@distributors.count, 'Distributor')%>; 
<%= pluralize(@dcs.count, 'DC')%>;
<% if @banners %>
	<%= pluralize(@banners.count, 'Banner') %>
<% end %>

<article>
<%-# START table header  -%>
<table>
<col width = "250">  
<col width = "50" >
<% (1..12).each do |i| %>  
	<col width = "60" >
<% end %>
  <tr><th>Distributor/DC</th>
    	<th align="right">rank:</th>
			<% @ranked_flavors.each do |flavor| %>
	  		<th><%= flavor.rank %></th>
			<% end %>
	</tr>
  <tr><th>to Banners</th>
    	<th>ct/avg</th>
			<% @ranked_flavors.each do |flavor| %>
	  		<th><%= flavor.shorthand %></th>
			<% end %>
	</tr>
<%-# END table header   -%>

	<%-# START first level outline is distributors   -%>
	<% @distributors.each do |distributor| %>
	<strong><tr class="distributorrow"><td><%= link_to(distributor.distributor_name, distributor) %> <%= distributor.stocking_dcs_count %> of <%= pluralize(distributor.dc_count, 'DC') %></td></tr></strong>

			<%-# START 2 level outline is DCs   -%>
				<% @dcs.where(distributor: distributor).each do |dc| %>
				<tr class="dcrow"><td class="indent1"><%= link_to(dc.dc_name, distributor_dc_path(distributor, dc)) %> <%= number_to_currency(dc.listprice) %> </td>

				<%-# START 3a level outline is DC Slots   -%>
					<%-# START DC Slots leftmost column   -%>
					<th><%= link_to(dc.dc_slots.size, edit_distributor_dc_path(distributor, dc)) %></th>
					<%-# END DC Slots leftmost column   -%>

					<%-# START DC Slots flavor columns  -%>
					<% @ranked_flavors.each do |flavor| %>
						<% if dc.dc_slots.includes(:fgsku).pluck(:flavor_id).include? flavor.id %>
							<th><%= flavor.shorthand %></th>
						<% else %>
							<th bgcolor="white"></th>
						<% end %>
					<% end %>

				</tr>
					<%-# END DC Slots flavor columns  -%>
				<%-# END 3a level outline is DC Slots   -%>


				<% if @banners %>
					<%-# START 3b level outline is Banners   -%>
						<% @banners.where(dc: dc).each do |banner| %>
						<i>
						<tr class="bannerrow"><td class="indent2"><%= link_to(banner.banner_name, parent_banner_path(banner.parent,banner)) %> <%= banner.our_banner_store_count %>/<%= pluralize(banner.banner_store_count, 'Str')%> (<%= number_to_percentage(banner.our_store_percent, precision: 0) %>)</td>
						<th><%= banner.average_bssw.round(1) %></th>

						<%# START 4 level outline is Authorizations   %>
						<% @ranked_flavors.each do |flavor| %>
							<% if banner.authorizations.includes(:fgsku).pluck(:flavor_id).include? flavor.id %>
							<% this_auth = banner.authorizations.includes(:fgsku).find_by(:flavor_id)  %>
	 						<td class = "present"><%= banner.auth_flavor_bssw_hash[flavor.shorthand].round(1).to_s %></td>
							<% else %>
								<td class ="absent"></td>
							<% end %>
						<% end %>
						</tr>
						</i>
						<%-# END 4 level outline is Authorizations   -%>
					<% end %>
				<% end %>
				
				<%-# END 3b level outline is Banners   -%>

			<% end %>
			
			<%-# END 2 level outline is DCs   -%>

	<% end %>
				
	<%-# END first level outline is distributors   -%>
</table>
	
</article>

app/views/distributors/new.html.erb
<article>
	<header>

	<h1>New Distributor </h1>

	<%= render 'distributorform' %>

	</header>
</article>

app/views/distributors/show.html.erb
<% content_for(:title, @distributor.distributor_name) %>
<article id="parent" class="parent">
	<header>
		<h1><%= @distributor.distributor_name %></h1>
	</header>
		<p> <%= @distributor.channel_segment %></p>
	
		<p> <%= @distributor.distributor_contact_first_name %> <%= @distributor.distributor_contact_last_name %></p>
		<p> <%= @distributor.distributor_city %>, <%= @distributor.distributor_state %> </p>
		<p> Distributor Level Notes:<br/> <%= @distributor.distributor_notes %> </p>

  <footer>
		<% if current_user_admin? %>
	    <nav>
				<%= link_to 'Edit this Distributor', edit_distributor_path(@distributor), class: 'button'  %>
				<%= link_to 'Delete this Distributor', distributor_path(@distributor), 
										class: 'button', 
										method: :delete, data: {confirm: "Are you sure you want to delete #{@distributor.distributor_name}?"}  %>
	    </nav>
	  <% end %>
  </footer>
</article>

<% content_for(:side) do %>
	<h3><%= pluralize(@distributor.dcs.size, 'DC') %></h3>
	<table>
	<tr>
		<th></th>
		<th>Default</th>
		<th>Served</th>
	</tr>
	<tr>
		<th>DC</th>
		<th>Banners</th>
		<th>Stores</th>
	</tr>
		<% cumestores = 0 %>
		<% cumebanners = 0 %>
			<% @distributor.dcs.order("dc_name").each do |dc| %>
				<article class="parent">
				<tr>
					<td align="right"><strong><%= link_to(dc.dc_name, distributor_dc_path(@distributor,dc)) %></strong></td>
					<% bannercount = Banner.where(dc_id: dc).size %>
					<td align="center"><%= bannercount %></td>
					<% cumebanners += bannercount %>
					<% storecount = Store.where(dc_id: dc).size %>
					<td align="center"><%= storecount %></td>
					<% cumestores += storecount %>
				</tr>
			<% end %>
			
			<tr>
				<th align="right">Total:</th>
				<th align="center"><%= cumebanners %></th>
				<th align="center"><%= cumestores %></th>
			</tr>
		</table>
			
<% if current_user_admin? %>
		<%= link_to "Add a DC", new_distributor_dc_path(@distributor), class: "button ok addbanner" %>
	<% end %>
<% end %>	