config/routes.rb
Rails.application.routes.draw do

  root "distributors#index"
  resource :session

  get "signup" => "users#new"
  resources :users

  resources :logs
  resources :managers
  resources :zing_leads
  resources :brokers
  resources :brokerages

  get "distributors/filter/:coverage" => "distributors#index", as: :filtered_distributors
  resources :distributors do
    resources :dcs do
      resources :dc_slots
      resources :dc_cost_lists
    end
  end

  resources :flavors do 
    resources :fgskus
    resources :recipes do
      resources :recipeversions
    end
  end

  resources :ingredients do
    resources :ingredientskus
  end

  resources :parents do
 	  resources :banners do
 	  	resources :stores
		  resources :banner_promos
      resources :authorizations
      resources :banner_cost_retails
 	  end
 	end

end

app/models/store.rb
class Store < ActiveRecord::Base

	extend FriendlyId
	friendly_id :store_name, use: :slugged

	validates :store_name, presence: true, uniqueness: {scope: :banner, message: "already exists for this banner"}
#	validates :slug, uniqueness: true
	validates :dc_id, presence: true

  belongs_to :banner
  belongs_to :dc
  has_many :logs

#  before_validation :generate_slug

  def to_param
		slug
	end

	# def generate_slug
	# 	self.slug ||= store_name.parameterize if store_name
	# end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

	before_action :set_parent
	before_action :set_banner
	before_action :set_store, only: [:show, :edit, :update, :destroy] 

	def index		
	end

	def show
	end

	def edit
	end

	def update
		if @store.update(store_params)
			redirect_to parent_banner_store_path, notice: "Store successfully updated"			
		else
			render :edit
		end
	end

	def new
		@store = @banner.stores.new
	end

	def create
		@store = @banner.stores.new(store_params)
		if @store.save
			redirect_to parent_banner_path(@banner.parent, @banner), notice: "New store in #{@store.city}, #{@store.state} created"
		else
			render :new
		end
	end

	def destroy
		deleted = @store.store_name
		@store.destroy
		redirect_to parent_banner_stores_path, notice: "#{deleted} store deleted"
	end

end

private
	def store_params
				params.require(:store).permit(
							:street_address,
							:city,
							:state,
							:zip,
							:dc_id,
							:store_name,
							:slug
							)
	end
	def set_parent
		if @banner
			@parent = @banner.parent
		elsif params[:parent_id].present?
			@parent = Parent.find_by!(slug: params[:parent_id])
		else
			@parent = Parent.find_by!(slug: params[:id])
		end
	end

	def set_banner
		if @store
			@banner = @store.banner
		elsif params[:banner_id].present?
			@banner = Banner.find_by!(slug: params[:banner_id])
		else
			@banner = Banner.find_by!(slug: params[:id])
		end
	end

	def set_store
		@store = Store.find_by!(slug: params[:id])
	end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_storeform.html.erb
<%= form_for [@banner.parent, @banner, @store] do |f| %>
  <%= render 'shared/errors', object: @store %>
	<fieldset>
	<ol>
		<li class="required"><%= f.label :store_name %> <%= f.text_field :store_name, size: 65, autofocus: true %></Li>

		<li class="required"> <%= f.label "Distributor & DC:" %>
			<% Distributor.all.order("distributor_name").each do |distributor| %>
				<% if @store.dc && @store.dc.distributor_id == distributor.id %>
						<strong><font color="red"> <%= distributor.distributor_name %>: </strong></font>
					<% else %>
						<%= distributor.distributor_name %>:
				<% end %>
					
				<% Dc.where(distributor_id: distributor.id).order("dc_name").each do |dc| %>
					<table>
						<tr>
							<td>
								<%= f.radio_button :dc_id, dc.id  %>  
							</td>
							<td>
							<% if @store.dc_id == dc.id %>
								<strong><font color="red"> <%= dc.dc_name %> </strong></font>
							<% else %>
								<%= dc.dc_name %>
								<% end %>
							</td>
						</tr>
					</table>			
				<% end %>
			<% end %>
		</li>

		<li class="required"><%= f.label :street_address %> <%= f.text_field :street_address, size: 65%></Li>
		<li class="required"><%= f.label :city %> <%= f.text_field :city %></Li>
		<li class="required"><%= f.label :state %> <%= f.text_field :state %></Li>
		<li class="required"><%= f.label :zip %><%= f.text_field :zip%></Li>

		<p>
			<%= f.submit %>
			<% if @store.id %>
				<%= link_to 'CANCEL', parent_banner_store_path, class: 'button'%>
			<% else %>
				<%= link_to 'CANCEL', parent_banner_stores_path, class: 'button'%>
			<% end %>
		</p> 

		</ol>
	</fieldset>

<% end %>

app/views/stores/edit.html.erb
<article>
	<header>

	<h1>Editing Store: <%= @store.store_name %> in <%= link_to(@banner.banner_name, @parent ) %> </h1>

	<%= render 'storeform' %>

	</header>
</article>

app/views/stores/index.html.erb
<header>
	<h1><%= pluralize(@banner.stores.size, 'Store') %> </h1> 
	for <%= link_to(@banner.parent.corpname, @banner.parent) %> 
	<%= link_to(@banner.banner_name, parent_banner_path(@banner.parent, @banner)) %> 
</header>

<% storecume = 0 %>

<ol>
	<% @banner.stores.order("store_name").each do |store| %>

	<article class="parent">
			<li>
				<strong>
					<%= link_to(store.store_name, parent_banner_store_path(@banner.parent,@banner,store)) %>
				</strong>
			</li>
	</article>

	<% end %>
</ol>

app/views/stores/new.html.erb
<article>
	<header>

	<h1>New Store for <%= link_to(@banner.banner_name, @parent ) %> </h1>

	<%= render 'storeform' %>

	</header>
</article>

app/views/stores/show.html.erb
<article id="parent" class="parent">
	<header>
		<%= link_to(@store.banner.parent.corpname, parent_path(@store.banner.parent)) %><br/>
		<%= link_to(@store.banner.banner_name, parent_banner_path(@store.banner.parent, @store.banner)) %><br/>
		<i>Store:</i> 
		<h1><%= @store.store_name %></h1>
	</header>
		Distributor DC: <%= link_to(@store.dc.distributor.distributor_name, distributor_path(@store.dc.distributor )) %> 
		<%= link_to(@store.dc.dc_name, distributor_dc_path(@store.dc.distributor, @store.dc)) %>
		
  <footer>
		<% if current_user_admin? %>
	    <nav>
				<%= link_to 'Edit this Store', edit_parent_banner_store_path(@banner.parent, @banner, @store), class: 'button'  %>
				<%= link_to 'Delete this Store', parent_banner_store_path(@banner.parent, @banner, @store), 
										class: 'button', 
										method: :delete, data: {confirm: "Are you sure you want to delete #{@store.store_name}?"}  %>
	    </nav>
	  <% end %>
  </footer>

</article>