config/routes.rb
Rails.application.routes.draw do

  root "distributors#index"
  resource :session

  get "signup" => "users#new"
  resources :users

  resources :logs
  resources :managers
  resources :zing_leads
  resources :brokers
  resources :brokerages

  get "distributors/filter/:coverage" => "distributors#index", as: :filtered_distributors
  resources :distributors do
    resources :dcs do
      resources :dc_slots
      resources :dc_cost_lists
    end
  end

  resources :flavors do 
    resources :fgskus
    resources :recipes do
      resources :recipeversions
    end
  end

  resources :ingredients do
    resources :ingredientskus
  end

  resources :parents do
 	  resources :banners do
 	  	resources :stores
		  resources :banner_promos
      resources :authorizations
      resources :banner_cost_retails
 	  end
 	end

end

app/models/banner.rb
class Banner < ActiveRecord::Base
	extend FriendlyId
	friendly_id :banner_name, use: :slugged

	before_validation :initialize_actual_cost
  before_validation :initialize_banner_store_count
  before_validation :initialize_our_banner_store_count
	before_validation :initialize_actual_cost

	validates :banner_name, presence: true, uniqueness: {scope: :parent, message: "already exists for this parent company"}
	validates :country, presence: true
	validates :banner_store_count, allow_blank: true, numericality: {
		only_integer: true, greater_than: -1,
		message: "must be positive"
	}
	validates :logo_file_name, allow_blank: true, format: {
		with: /\w+\.(gif|jpg|png|bmp)\z/i,
		message: "must reference a GIF, JPG, PNG or BMP image"
	}

  belongs_to :parent
	belongs_to :dc
	belongs_to :broker
	has_many :stores, dependent: :destroy
	has_many :banner_promos, dependent: :destroy
	has_many :logs
	has_many :authorizations, dependent: :destroy
	has_many :authorized_fgskus, through: :authorizations, source: :fgsku
	has_many :banner_cost_retails


  scope :all_banners, -> { Banner.all.order("banner_name") }
  scope :current_banners, -> { Banner.joins(:authorizations).distinct.order("banner_name") }
  scope :prospect_banners, -> { Banner.where.not(id: Authorization.select(:banner_id)).order("banner_name") }
  scope :priority_banners, -> { Banner.where("priority > ?", 0).order("priority") }

	def to_param
		"#{id}-#{banner_name.parameterize}"
	end

# BANNER LEVEL FIXED -----------------------------------------
	def nominal_retail_margin_pct
		cost = (self.dc.listprice || 0 ) / 12
		shelf = self.bar_regular_retail
		if shelf 
			margin_pct = (shelf - cost) / shelf
		else
			0
		end
	end

	def nominal_retail_margin_dollars
		cost = (self.dc.listprice || 0 ) / 12
		shelf = self.bar_regular_retail
		if shelf 
			margin_dollars = (shelf - cost)
		else
			0
		end
	end

	def actual_retail_margin_pct
		cost = (self.caddy_actual_cost  || 0 ) / 12
		shelf = self.bar_regular_retail
		if shelf && caddy_actual_cost
			margin_pct = (shelf - cost) / shelf
		else
			0
		end
	end

	def actual_retail_margin_dollars
		cost = (self.caddy_actual_cost  || 0 ) / 12
		shelf = self.bar_regular_retail
		if shelf && caddy_actual_cost
			margin_dollars = (shelf - cost) 
		else
			0
		end
	end

	def our_store_percent
		100 * self.our_banner_store_count.to_f / self.banner_store_count.to_f
	end

	def noreviewdate
		banner_review_date <= Date.today
	end

#to refactor; also in dc.rb
	def available_fgskus
		Fgsku.where(country: self.country).includes(:flavor).order('sizegroup', "flavors.shorthand")
	end

	def has_authorizations
		authorizations.any?
	end

	def total_authorizations
		self.authorized_fgskus.size
	end

	def auth_flavor_bssw_hash
		this_hash = {}
		self.authorizations.each do |authorization|
			key = authorization.fgsku.flavor.shorthand
			value = authorization.bssw
			this_hash.store(key, value)
		end
		this_hash
	end

	def cume_bssw
		if self.authorizations.present?
			self.authorizations.inject(0) { |sum, e| sum += e.bssw }.round(2)
		else
			0
		end
	end

	def average_bssw
		if self.total_authorizations > 0 
			average_bssw = cume_bssw / total_authorizations
		else
			average_bssw = 0
		end
	end

	def barsperweekbase
		if self.authorizations.present?
			self.authorizations.inject(0) { |sum, auth| sum += auth.bssw * self.our_banner_store_count }.round(2)
		else
			0
		end
	end

	# QUARTERLIES -------------------------------------------------

	def quarter_gross_base
		self.cume_bssw * self.banner_store_count * 13 * Fgsku::FULLSIZECADDYPRICE / 12
	end

	def quarter_bars_base
		self.barsperweekbase * 13
	end

	def quarter_gross_lift(year,quarter)
		self.banner_quarter_lift_bars(year,quarter) * Fgsku::FULLSIZECADDYPRICE / 12
	end

	def quarter_gross_total(year,quarter)
		self.quarter_gross_base + quarter_gross_lift(year,quarter)
	end

	def quarter_start_date(year, quarter)
		quarter_start_month = 3 * (quarter -1) + 1
		Date.new(year,quarter_start_month,1)
	end

	def quarter_end_date(year, quarter)
		quarter_end_month = 3 * quarter 
		Date.new(year,quarter_end_month,-1)
	end

	def banner_quarter_promos(year,quarter)
		self.banner_promos.where( start_date: (quarter_start_date(year, quarter)..quarter_end_date(year,quarter) ) )
	end

	def banner_quarter_lift_bars(year,quarter)
		lift_bars = 0
		self.banner_quarter_promos(year,quarter).each do |promo|
			lift_bars += promo.total_promo_lift_bars
		end
		lift_bars
	end

	def banner_quarter_total_bars(year,quarter)
		self.quarter_bars_base + self.banner_quarter_lift_bars(year,quarter)
	end

	def banner_quarter_formula_spend(year,quarter)
		formula_spend = 0
		self.banner_quarter_promos(year,quarter).each do |promo|
			formula_spend += promo.total_formula_spend
		end
		formula_spend
	end

	def banner_quarter_lump_spend(year,quarter)
		lump_spend = 0
		self.banner_quarter_promos(year,quarter).each do |promo|
			lump_spend += promo.total_lump_spend
		end
		lump_spend
	end

	def banner_quarter_promo_spend(year,quarter)
		self.banner_quarter_formula_spend(year,quarter) + self.banner_quarter_lump_spend(year,quarter)
	end

	def banner_quarter_formula_spend_percent(year,quarter)
		self.banner_quarter_formula_spend(year,quarter) / quarter_gross_total(year,quarter)
	end

	def banner_quarter_lump_spend_percent(year,quarter)
		self.banner_quarter_lump_spend(year,quarter) / quarter_gross_total(year,quarter)
	end

	def banner_quarter_total_spend_percent(year,quarter)
		self.banner_quarter_formula_spend_percent(year,quarter) + banner_quarter_lump_spend_percent(year,quarter)
	end


	# ANNUALS -------------------------------------------------

	def annual_gross_base
		self.cume_bssw * self.our_banner_store_count * 52 * Fgsku::FULLSIZECADDYPRICE / 12
	end

	def year_gross_lift(year)
		self.banner_year_lift_bars(year) * Fgsku::FULLSIZECADDYPRICE / 12
	end

	def annual_gross_total(year)
		self.annual_gross_base + self.year_gross_lift(year)
	end

	def annual_gross_lift_percent(year)
		 self.year_gross_lift(year) / self.annual_gross_base
	end

	def annual_brokerage
		self.annual_gross_base * self.broker.brokerage.rate / 100
	end

	def year_bars_base
		self.barsperweekbase * 365 / 7
	end

	def annual_vc_base
		Fgsku::FULLSIZECADDYVCPREPROMO * year_bars_base / 12
	end

	def annual_vc_base_percent
		self.annual_vc_base / self.annual_gross_base
	end

	def year_start_date(year)
		Date.new(year,1,1)
	end

	def year_end_date(year)
		Date.new(year,12,31)
	end

	def banner_year_promos(year)
		self.banner_promos.where( start_date: (year_start_date(year)..year_end_date(year) ) )
	end

	def banner_year_lift_bars(year)
		lift_bars = 0
		self.banner_year_promos(year).each do |promo|
			lift_bars += promo.total_promo_lift_bars
		end
		lift_bars
	end

	def banner_year_total_bars(year)
		self.year_bars_base + self.banner_year_lift_bars(year)
	end

	def annual_vc_pre_promo(year)
		Fgsku::FULLSIZECADDYVCPREPROMO * banner_year_total_bars(year) / 12
	end

	def annual_vc_pre_promo_percent(year)
		self.annual_vc_pre_promo(year) / self.annual_gross_total(year)
	end

	def annual_vc_post_promo(year)
		self.annual_vc_pre_promo(year) - self.banner_year_promo_spend(year)
	end

	def annual_vc_post_promo_percent(year)
		self.annual_vc_post_promo(year) / self.annual_gross_total(year)
	end

	def annual_vc_promo_change_percent(year)
		self.annual_vc_post_promo(year) / self.annual_vc_base - 1
	end

	def banner_year_formula_spend(year)
		formula_spend = 0
		self.banner_year_promos(year).each do |promo|
			formula_spend += promo.total_formula_spend
		end
		formula_spend
	end

	def banner_year_formula_spend_percent(year)
		self.banner_year_formula_spend(year) / annual_gross_total(year)
	end

	def banner_year_lump_spend(year)
		lump_spend = 0
		self.banner_year_promos(year).each do |promo|
			lump_spend += promo.total_lump_spend
		end
		lump_spend
	end

	def banner_year_lump_spend_percent(year)
		self.banner_year_lump_spend(year) / annual_gross_total(year)
	end

	def banner_year_promo_spend(year)
		self.banner_year_formula_spend(year) + self.banner_year_lump_spend(year)
	end

	def banner_year_promo_spend_percent(year)
		self.banner_year_formula_spend_percent(year) + banner_year_lump_spend_percent(year)
	end



# SETUPS -----------------------------------------------------

	def to_param
		slug
	end

 	def initialize_banner_store_count
  	self.banner_store_count = 1 unless banner_store_count
  end
	def initialize_our_banner_store_count
  	self.our_banner_store_count = 0 unless our_banner_store_count
  end
  def initialize_actual_cost
		self.caddy_actual_cost = ( Fgsku::FULLSIZECADDYPRICE * 100.0 * 4.0 / 3.0).round / 100 unless caddy_actual_cost
	end
 
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController

	before_action :set_parent
	before_action :set_banner, only: [:show, :update, :edit, :destroy]

	def index
		@banners = @parent.banners
	end
	
	def show
		@banner = Banner.find_by!(slug: params[:id])
	end
	
	def edit		
	end
	
	def update
		if @banner.update(banner_params)
			redirect_to parent_banner_path, notice: 'Banner successfully updated'
		else
			render :edit
		end
	end
	
	def new
		@banner = @parent.banners.new
	end
	
	def create
		@banner = @parent.banners.new(banner_params)
		if @banner.save
			redirect_to parent_banners_path(@parent), notice: "New retail banner #{@banner.banner_name} created"
		else
			render :new
		end
	end
	
	def destroy
		deleted = @banner.banner_name
		@banner.destroy
		redirect_to parent_banners_path, notice: "#{deleted} deleted"
	end

end

private
	def banner_params
				params.require(:banner).permit(
							:banner_name,
							:banner_city,
							:banner_state,
							:banner_buyer_first_name,
							:banner_buyer_last_name,
							:banner_broker_first_name,
							:banner_broker_last_name,
							:banner_review_date,
							:banner_store_count,
							:our_banner_store_count,
							:banner_notes,
							:logo_file_name,
							:country,
							:dc_id,
							:priority,
							:slug,
							:broker_id,
							:bar_regular_retail,
							:caddy_actual_cost,
							:bar_feature_price,
							:performance,
							authorized_fgsku_ids: []
							)
	end
	def set_parent
		if @banner
			@parent = @banner.parent
		elsif params[:parent_id].present?
			@parent = Parent.find_by!(slug: params[:parent_id])
		else 
			@parent = Parent.find_by!(slug: params[:id])
		end
	end

	def set_banner
		if @banner
			@banner = Banner.find_by!(slug: params[:id])
		elsif params[:banner_id].present?
			@banner = Banner.find_by!(slug: params[:banner_id])
		else
			@banner = Banner.find_by!(slug: params[:id])
		end

	end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_bannerform.html.erb
<%= form_for([@parent, @banner]) do |f| %>
  <%= render 'shared/errors', object: @banner %>

	<fieldset>
		<table class="required">
			<% (1..5).each do |i| %>  
				<col width = "250" >
			<% end %>

			<tr>
				<td colspan="2" class="required"><%= f.label :banner_name %> <%= f.text_field :banner_name, size: 40, autofocus: true %></td>
			
				<td class="required"><%= f.label "Priority (5=Highest)" %>
					<% [5,4,3,2,1,0].each do |priority| %>
						<%= f.radio_button :priority, priority %>
						<%= priority %></br>
					<% end %>
				</td>		

				<td class="required"><%= f.label :country %>
					<% Fgsku::COUNTRIES.each do |country| %>
						<%= f.radio_button :country, country %>
						<%= country %></br>
					<% end %>
				</td>

			</tr>

			<tr><td>&nbsp;</td></tr>

			<tr>
				<td class="required"><%= f.label :bar_regular_retail %> <%= f.number_field :bar_regular_retail, :class => 'text_field', :step => 0.01 %></td>
				<td class="required"><%= f.label :caddy_actual_cost %> <%= f.number_field :caddy_actual_cost, :class => 'text_field', :step => 0.01 %></td>
					<td colspan = "2" class="required">
						<% unless @banner.dc.nil? %>
							Caddy List Cost from <%= @banner.dc.distributor.distributor_name %> <%= @banner.dc.dc_name %>: <%= number_to_currency(@banner.dc.listprice) %>
						<% end %>
					</td>
			</tr>

			<tr><td>&nbsp;</td></tr>

			<tr>
				<td class="required"><%= f.label :banner_store_count %> <%= f.number_field :banner_store_count %></td>
				<td class="required"><%= f.label :our_banner_store_count %> <%= f.number_field :our_banner_store_count %></td>				
				<td class="required"><%= f.label :banner_review_date %> <%= f.date_field :banner_review_date %></td>
				<td class="required"><%= f.label :banner_city %><%= f.text_field :banner_city%></td>
				<td class="required"><%= f.label :banner_state %><%= f.text_field :banner_state%></td>
			</tr>

			<tr>
				<td class="required"><%= f.label :banner_buyer_first_name %><%= f.text_field :banner_buyer_first_name%></td>
				<td class="required"><%= f.label :banner_buyer_last_name %><%= f.text_field :banner_buyer_last_name%></td>
				<td class="required"><%= f.label :logo_file_name %> <%= f.text_field :logo_file_name, placeholder: "GIF, JPG or PNG file name" %></td>
			</tr>

			<tr>
				<td colspan="5" class="required"><%= f.label :banner_notes %> <%= f.text_area :banner_notes, cols: 120, rows: 7  %></td>
			</tr>

			<tr>
				<td class="required"> <%= f.label "Banner Default DC:" %>
					<% linecount = 0 %>
					<% totallines = Distributor.all.count + Dc.all.count %>	
					<% breakline = totallines / 2 %>
					<% Distributor.all.order("distributor_name").each do |distributor| %>
						<b><i>
							<% if @banner.dc && @banner.dc.distributor_id == distributor.id %>
									<strong><font color="red"> <%= distributor.distributor_name %> </br></font></strong>
								<% else %>
									<%= distributor.distributor_name %></br>
							<% end %>
							<% linecount += 1 %>
						</i></b>

						<% Dc.where(distributor_id: distributor.id).order("dc_name").each do |dc| %>
							<%= f.radio_button :dc_id, dc.id  %>
							<% if @banner.dc_id == dc.id %>
									<strong><font color="red"> <%= dc.dc_name %> </br></font></strong>
								<% else %>
									<%= dc.dc_name %></br>
							<% end %>
						<% linecount += 1 %>
						<% end %>

						<% if linecount >= breakline %>
							</td><td>
							<% linecount = 0 %>
						<% end %>
					<% end %>
				</td>
			</td>

			<td>
				<strong><%= f.label 'Authorizations:' %></strong>
				<%= f.collection_check_boxes(:authorized_fgsku_ids, @banner.available_fgskus, :id, :flavor_descriptor) %>
			</td>

				<td class="required"> <%= f.label "Banner Broker:" %>
					<% linecount = 0 %>
					<% Brokerage.all.order("company").each do |brokerage| %>
						<b><i>
							<% if @banner.broker && @banner.broker.brokerage_id == brokerage.id %>
									<strong><font color="red"> <%= brokerage.company %>:</br></font></strong>
								<% else %>
									<%= brokerage.company %>:</br>
							<% end %>
							<% linecount += 1 %>
						</i></b>

						<% Broker.where(brokerage_id: brokerage.id).order("last_name").each do |broker| %>
							<%= f.radio_button :broker_id, broker.id  %>
								<% if @banner.broker_id == broker.id %>
									<strong><font color="red"> <%= broker.first_name %> <%= broker.last_name %></br></font></strong>
								<% else %>
									<%= broker.first_name %> <%= broker.last_name %></br>
								<% end %>
							<% linecount += 1 %>
							<% end %>

							<% if linecount >= breakline %>
								</td><td>
								<% linecount = 0 %>
							<% end %>
						<% end %>
				</td>

		</tr>

		</table>

		<p>
			<%= f.submit %>
			<%= link_to 'CANCEL', :back, class: 'button'%>
		</p>

	</fieldset>

<% end %>

app/views/banners/_channeleconomicstable.html.erb
<table>
	<col width = "140"> 
	<col width = "50" >
	<col width = "50" >
	<col width = "50" >
	<col width = "50" >
	<col width = "50" >

	<tr class="bannerrow" align="center">
		<td align="left"><em><b>Channel Economics</b></em></td>
		<td>Bar</td>
		<td>Caddy</td>
		<td>$Mgn</td>
		<td>MkUp%</td>
		<td>Mgn%</td>
	</tr>
	
	<tr class="bannerrow" align="right">
		<td><%= link_to(@banner.dc.dc_name, distributor_dc_path(@banner.dc.distributor, @banner.dc))%> List Cost</td>
		<td><%= number_to_currency(@banner.dc.listprice / 12, precision: 2) %></td>
		<td><%= number_to_currency(@banner.dc.listprice) %></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>

	<tr class="bannerrow" align="right">
		<td>DC Actual Cost</td>
		<td><%= number_to_currency(@banner.caddy_actual_cost / 12, precision: 2) %></td>
		<td><%= number_to_currency(@banner.caddy_actual_cost, precision: 2) %></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>

	<tr class="bannerrow" align="right">
		<td>Retail</td>
		<td><%= number_to_currency(@banner.bar_regular_retail) %></td>
		<td></td>
		<td><%= number_to_currency(@banner.actual_retail_margin_dollars) %></td>
		<td></td>
		<td><%= number_to_percentage(@banner.actual_retail_margin_pct * 100, precision: 2) %></td>
	</tr>

</table>

app/views/banners/_promoflowchart.html.erb
<%= render 'promotablelayout' %>

	<%# START banner_promos     %>
	<tr class="bannerrow">
		<td><%= link_to(promo.comment, edit_parent_banner_banner_promo_path(@banner.parent, @banner, promo )) %></td>
		<td align="center"><%= promo.promo_vehicle %> </td>
		<td align="center"><%= promo.promo_method %> </td>

		<td align="center">
			<%= banner_promo_basis_text(promo.promo_vehicle, promo.promo_method, promo.promo_level)%> 
		</td>
		
		<td align="center"><%= number_to_currency(promo.dollars_per_bar) %> </td>
		<td align="center">
			<%= number_to_percentage(promo.percent_of_list * 100, precision: 1) %> 
		</td>
		<td align="center"><%= number_to_currency(promo.bar_feature_price) %></td>

		<td align="center"><%= number_to_currency(promo.promo_margin_dollars) %></td>
		<td align="center"><%= number_to_percentage(promo.promo_margin_pct * 100, precision: 1) if promo.promo_margin_pct%></td>

		<td align="center">
			<% if promo.lift.present? && promo.lift != 0 %>
				<%= number_to_percentage(promo.lift*100, precision: 0)  %>
			<% end %>
		</td>

		<% (1..52).each do |i| %>  
			<% if (promo.startweek..promo.endweek).include?(i) %>
				<td class = "<%= promo.status.downcase %>" ></td>
			<% else %>
				<td></td>
			<% end %>
		<% end %>


	</tr>
</table>

app/views/banners/_promoflowchartheader.html.erb
  <%= render 'promotablelayout' %>
	<% leftcolumncount = 8 %>

	<tr class="bannerrow" align="center">
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>% of</td>
		<td colspan="3">Feature</td>
		<td></td>
		<td colspan="52">Year</td>
	</tr>

	<tr class="bannerrow" align="center">
		<td>Promo Description</td>
		<td></td>
		<td></td>
		<td></td>
		<td>$/</td>
		<td>Zing</td>
		<td>Shelf</td>
		<td colspan="2">Retail Mgn</td>
		<td>%</td>
		
		<% (1..4).each do |i| %>  
			<td colspan="13" align="center"><%= i %>Q</td>
		<% end %>
	</tr>
	
	<tr class="bannerrow" align="center">
		<td>(click to edit)</td>
		<td>Vehicle</td>
		<td>Method</td>
		<td>Basis</td>
		<td>Bar</td>
		<td>List</td>
		<td>Price</td>
		<td>$</td>
		<td>%</td>
		<td>Lift</td>

		<% (1..52).each do |i| %>
			<% if (Date.today.strftime("%W").to_i >= i) %>
				<td class = "currentweek" ></td>
			<% else %>
				<td></td>
			<% end %>
		<% end %>
	</tr>

</table>

app/views/banners/edit.html.erb
<article>
	<header>

	<h1>Editing <%= @banner.banner_name %></h1>
	<%= render 'bannerform' %>

	</header>
</article>

app/views/banners/show.html.erb
<% content_for(:title, @banner.banner_name) %>
<article id="parent" class="parent">
	<header>
		Parent: <% parent = @banner.parent %> <%= link_to(parent.corpname, parent_path(parent)) %> <br />
		DC: <%= link_to(@banner.dc.distributor.distributor_name, distributor_path(@banner.dc.distributor)) %> <%= link_to(@banner.dc.dc_name, distributor_dc_path(@banner.dc.distributor, @banner.dc)) %>
		<%= image_for(@banner) %>
		<h1>Banner: <%= @banner.banner_name %></h1>
	</header>
	 We have <%= @banner.our_banner_store_count %> of their <%= pluralize(@banner.banner_store_count, 'store') %> (<%= number_to_percentage(100*@banner.our_banner_store_count.to_f/@banner.banner_store_count.to_f, precision: 0) %>) <br/>

	Priority: <%= @banner.priority %><br/>
	Broker: 
	<% if @banner.broker %>
		<%= @banner.broker.first_name %> <%= @banner.broker.last_name %>, <%= @banner.broker.brokerage.company %>; 
	Brokerage Rate <%= number_to_percentage(@banner.broker.brokerage.rate, precision: 1) %> ==>
	<%= number_to_currency(@banner.annual_brokerage, precision: 0) %> annual brokerage<br/>
	<% else %>
		NO BROKER ASSIGNED
	<% end %>  <br/>
	<%= @banner.banner_city %>, <%= @banner.banner_state %> <br/>
	Buyer: <%= @banner.banner_buyer_first_name %> <%= @banner.banner_buyer_last_name %><br/>
	Banner Level Notes:<br/> <%= @banner.banner_notes %> <br/>

	<%= render 'channeleconomicstable' %><br>

	<%= render 'oureconomicstable' %><br>

	<h2><%= pluralize(@banner.banner_promos.size, 'Promo') %>: 
	<%= number_to_percentage(100*@banner.banner_year_formula_spend_percent(2016), precision: 1) %> Formula Spend | 
	<%= number_to_percentage(100*@banner.banner_year_lump_spend_percent(2016), precision: 1) %> Lump Spend | 
	<%= number_to_percentage(100*@banner.banner_year_promo_spend_percent(2016), precision: 1) %> Total Spend
	</h2>	
		
		<%= render 'promoflowchartheader' %>
		<% @banner.banner_promos.order("start_date").each do |promo| %>
			<%= render 'promoflowchart', :promo => promo %>
			<% end %>

 	<%= link_to "Add a Promo", new_parent_banner_banner_promo_path(@parent,@banner),
  								class: "button ok addbanner" %>

	<h2><%= pluralize(@banner.stores.size, 'Store') %>:</h2>
		<ol>
		<% @banner.stores.order("store_name").each do |store| %>
				<li>
					<strong>
						<%= link_to(store.store_name, parent_banner_store_path(@banner.parent, @banner, store )) %> 
					</strong> 
						<%= store.city %>, <%= store.state %> :: 
						<i><%= store.dc.distributor.distributor_name %> <%= link_to(store.dc.dc_name, distributor_dc_path(store.dc.distributor, store.dc)) %></i>
				</li>
			<% end %>
		</ol>
  	<%= link_to "Add a Store", new_parent_banner_store_path(@parent,@banner),
  								class: "button ok addbanner" %>
 
  <footer>
  	<% if current_user_admin? %>
	    <nav>
				<%= link_to 'Edit this Banner', edit_parent_banner_path(@parent,@banner), class: 'button'  %>
				<%= link_to 'Delete this Banner', parent_banner_path(@banner.parent, @banner), 
										class: 'button', 
										method: :delete, data: {confirm: "Are you sure you want to delete #{@banner.banner_name}?"}  %>
	    </nav>
	  <% end %>
  </footer>

</article>

<% content_for(:side)	do %>
	<h3><%= pluralize(@banner.total_authorizations, 'FG SKU Authorization') %></h3>
		<article class="parent">
			<table>
				<th>SKU</th>
				<th>BSSW</th>
				<% cume_bssw = 0 %>

				<% @banner.authorized_fgskus.includes(:flavor).order('sizegroup', "flavors.shorthand").each do |fgsku| %>
					<tr>
						<td> <%= link_to(
							 "#{fgsku.flavor.shorthand} 
							 #{fgsku.country} 
							 #{fgsku.sizegroup}", flavor_fgsku_path(fgsku.flavor, fgsku)) %>
						</td>
						<td align="right">
							<% authorization = @banner.authorizations.find_by(fgsku: fgsku) %>
							<% authorization.bssw = 0 if authorization.bssw == nil %>
								<%= link_to(authorization.bssw.round(1), edit_parent_banner_authorization_path(@banner.parent, @banner, authorization)) %>
						</td>
					</tr>
				<% end %>

				<tr align="right">
					<td>Total BSW </td>
					<td><strong><%= @banner.cume_bssw.round(1) %></strong></td>
				</tr>
				<tr align="right">
					<td>x<%= pluralize(@banner.our_banner_store_count,"str") %>=Total Bars/Wk</td>
					<td><strong><%= @banner.barsperweekbase %></strong></td>
				</tr>
				<tr align="right">
					<td>Average BSSW </td>
					<td><strong><%= @banner.average_bssw.round(1) %></strong></td>
				</tr>
		</table>

	<nav>
	 	<%= link_to "Change SKU Authorizations", edit_parent_banner_path(@parent,@banner), class: "button" %>
	</nav>
<% end %>