config/routes.rb
Rails.application.routes.draw do

  root "distributors#index"
  resource :session

  get "signup" => "users#new"
  resources :users

  resources :logs
  resources :managers
  resources :zing_leads
  resources :brokers
  resources :brokerages

  get "distributors/filter/:coverage" => "distributors#index", as: :filtered_distributors
  resources :distributors do
    resources :dcs do
      resources :dc_slots
      resources :dc_cost_lists
    end
  end

  resources :flavors do 
    resources :fgskus
    resources :recipes do
      resources :recipeversions
    end
  end

  resources :ingredients do
    resources :ingredientskus
  end

  resources :parents do
 	  resources :banners do
 	  	resources :stores
		  resources :banner_promos
      resources :authorizations
      resources :banner_cost_retails
 	  end
 	end

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :banner
  belongs_to :fgsku

  before_validation :initialize_bssw

#to refactor; also in dc_slot.rb
	def flavor_descriptor
		"#{self.fgsku.flavor.shorthand} #{self.fgsku.sizegroup}"
  end

  def initialize_bssw
  	self.bssw = 0 unless bssw
  end
  
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController

	before_action :set_parent
	before_action :set_banner
	before_action :set_authorization, only:  [:show, :edit, :update, :destroy]

	def index
		fail
	end

	def show
	end

	def new
		@authorization = @banner.authorizations.new
		@fgskus = Fgsku.where(country: @banner.country)
		@authorization.bssw = 0
	end

	def create
		fail
	end

	def edit
 #   session[:return_to] ||= request.referer
	end

	def update
		@authorization = @banner.authorizations.find(params[:id])
		if @authorization.update(authorization_params)
#			redirect_to :back
#			redirect_to session.delete(:return_to), notice: "authorization updated"
			redirect_to parent_banner_path(@parent, @banner), notice: "authorization updated"
		else
			render :edit
		end
	end

end

private
	def authorization_params
		params.require(:authorization).permit(
																	:banner_id,
																	:fgsku_id,
																	:authdate,
																	:dropdate,
																	:bssw
																	)
	end

	def set_banner
		if @authorization
			@authorization.banner
		elsif params[:banner_id].present?
			@banner = Banner.find_by!(slug: params[:banner_id])
		else
			@banner = Banner.find_by!(slug: params[:id])
		end
	end

	def set_parent
		if @banner
			@parent = @banner.parent
		elsif params[:parent_id].present?
			@parent = Parent.find_by!(slug: params[:parent_id])
		else 
			@parent = Parent.find_by!(slug: params[:id])
		end
	end

	def set_authorization
		@authorization = Authorization.find(params[:id])
	end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/views/authorizations/_authorizationform.html.erb
<%= form_for([@banner.parent, @banner, @authorization]) do |f| %>
  <%= render 'shared/errors', object: @authorization %>
	<fieldset>
		<ol>

		<li class="required"><%= f.label :bssw %> <%= f.number_field :bssw, :class => 'text_field', :step => 0.01, autofocus: true %></Li>

		<li class="required"><%= f.label "authorization date" %> <%= f.date_field :authdate %></Li>
		<li class="required"><%= f.label "drop date" %> <%= f.date_field :dropdate %></Li>

		<p>
			<%= f.submit %>
			<% if @authorization.id %>
				<%= link_to 'CANCEL', parent_banner_authorization_path, class: 'button'%>
			<% else %>
				<%= link_to 'CANCEL', parent_banner_authorizations_path, class: 'button'%>
			<% end %>
		</p> 

		</ol>
	</fieldset>

<% end %>

app/views/authorizations/edit.html.erb
<article>
	<header>

	<h1>Editing Authorization: <%= @authorization.banner.banner_name %> <%= @authorization.fgsku.flavor.shorthand %></h1>

	<%= render 'authorizationform' %>

	</header>
</article>

app/views/authorizations/index.html.erb
<header>
	<h1><%= pluralize(@banner.authorizations.size, 'authorization') %> </h1> 
	for <%= link_to(@banner.parent.corpname, @banner.parent) %> 
	<%= link_to(@banner.banner_name, parent_banner_path(@banner.parent, @banner)) %> 
</header>

<ol>
	<% @banner.authorizations.each do |authorization| %>

	<article class="parent">
			<li>
				<strong>
					<%= link_to(authorization.flavor_descriptor, parent_banner_authorization_path(@banner.parent,@banner,authorization)) %> <%= authorization.bssw %>
				</strong>
			</li>
	</article>

	<% end %>
</ol>

@banner.authorized_fgskus.includes(:flavor).order('sizegroup', "flavors.shorthand")
@banner.authorizations.includes(:fgsku, :flavor).order('sizegroup', "flavors.shorthand")

app/views/authorizations/new.html.erb
<article>
	<header>

	<h1>New Authorization for <%= @banner.banner_name %></h1>
	 <%= Fgsku.where(country: @banner.country).count%> <%= @banner.country%> SKUs Available

	<%= render 'authorizationform' %>

	</header>
</article>

app/views/authorizations/show.html.erb
<article id="parent" class="parent">
	<header>
		<%= link_to(@authorization.banner.parent.corpname, parent_path(@authorization.banner.parent)) %><br/>
		<%= link_to(@authorization.banner.banner_name, parent_banner_path(@authorization.banner.parent, @authorization.banner)) %>

		<br/>
		<i>authorization:</i> 
		<h1><%= @authorization.fgsku.flavor.shorthand %></h1>
	</header>
		
  <footer>
		<% if current_user_admin? %>
	    <nav>
				<%= link_to 'Edit this authorization', edit_parent_banner_authorization_path(@banner.parent, @banner, @authorization), class: 'button'  %>
	    </nav>
	  <% end %>
  </footer>

</article>